version: "2"

services: 
  spring:
    build: .
    restart: always
    environment:
      # DATABASE SETTINGS, REQUIRED
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/temp_db
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev123
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.mariadb.jdbc.Driver
      ###############################################################
      # MAIL SETTINGS, REQUIRED
      - SPRING_MAIL_USERNAME=mail@example.com
      - SPRING_MAIL_PASSWORD=N0tTh3Actu4lP4SSw0rd
      - SPRING_MAIL_HOST=smtp.example.com
      - SPRING_MAIL_PORT=25
      # Uncomment and set these vars when using STARTTLS for mail sending
      # - SPRING_MAIL_PORT=587
      # - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      # - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      # Uncomment and set these vars when using SSL/TLS for mail sending
      # - SPRING_MAIL_PORT=465
      # - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      # - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE=true
      # - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SOCKETFACTORY_PORT=465
      # - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SOCKETFACTORY_CLASS=javax.net.ssl.SSLSocketFactory
      ###############################################################
      # OPTIONAL ARGS
      # - SERVER_PORT=8090
      # - DEBUG=true
      # - SPRING_THYMELEAF_CACHE=false
      # - LOGGING_LEVEL_WEB=DEBUG
    # network_mode: host
    ports: 
      - 8090:8090
